// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portfolio" | "/portfolio/:slug" | "/blog" | "/blog/:slug" | "/contact" | "/api/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/portfolio._index.tsx": {
    id: "routes/portfolio._index";
    page: "/portfolio";
  };
  "routes/portfolio.$slug.tsx": {
    id: "routes/portfolio.$slug";
    page: "/portfolio/:slug";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/api.contact.ts": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/portfolio._index": typeof import("./app/routes/portfolio._index.tsx");
  "routes/portfolio.$slug": typeof import("./app/routes/portfolio.$slug.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/api.contact": typeof import("./app/routes/api.contact.ts");
};